import os
TOKEN = 'BOT_TOKEN_GOES_HERE' or os.getenv('BOT_TOKEN')
PREFIX = '#'
SPOTIFY_CLIENT_ID = 'SPOTIFY_CLIENT_ID_GOES_HERE' or os.getenv('SPOTIFY_CLIENT_ID')
SPOTIFY_CLIENT_SECRET = 'SPOTIFY_CLIENT_SECRET_GOES_HERE' or os.getenv('SPOTIFY_CLIENT_SECRET')