name: Docker Image CI

on:
  push:
    branches:
      - "main"
      - "prod"  # Added prod branch to push trigger
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get IST timestamp
        id: datetime
        run: |
          DATETIME_IST=$(TZ="Asia/Kolkata" date +'%Y%m%d-%H%M%S')
          echo "DATETIME_IST=${DATETIME_IST}" >> $GITHUB_ENV

      - name: Determine tags
        id: tags
        run: |
          if [[ "$GITHUB_REF_NAME" == "main" ]]; then
            echo "TAG1=sayanpramanik/buff-discord-musicplayer:main_${{ env.DATETIME_IST }}" >> $GITHUB_ENV
            echo "TAG2=sayanpramanik/buff-discord-musicplayer:main_latestDev" >> $GITHUB_ENV
          elif [[ "$GITHUB_REF_NAME" == "prod" ]]; then
            echo "TAG1=sayanpramanik/buff-discord-musicplayer:prod_${{ env.DATETIME_IST }}" >> $GITHUB_ENV
            echo "TAG2=sayanpramanik/buff-discord-musicplayer:latest" >> $GITHUB_ENV
          elif [[ "$GITHUB_REF" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            SANITIZED_VERSION=$(echo "$VERSION" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
            echo "TAG1=sayanpramanik/buff-discord-musicplayer:$SANITIZED_VERSION" >> $GITHUB_ENV
            echo "TAG2=sayanpramanik/buff-discord-musicplayer:latest" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.TAG1 }}
            ${{ env.TAG2 }}
